# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 345eb7aef1b7a5ad2a8c569f0618e7085236556a6de229a9c3c7c49ce0b86351c588e1a90ad543c3c05d5094ca0e807e99124757933d42bacd6f45dd7b980e0d

production:
  secret_key_base: c149b788b98dd4b0d561ed317df7e56220de1606edd8c80b6b0c31200c87198a8c31f2afe33916a1b841c09aa8d44774eb06411b8013dca76c977549e5465591

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
